/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh;
    Object_5: THREE.Mesh;
    Object_6: THREE.Mesh;
    Object_7: THREE.Mesh;
    Object_10: THREE.Mesh;
    Object_11: THREE.Mesh;
    Object_12: THREE.Mesh;
    Object_9: THREE.Mesh;
    Object_14: THREE.Mesh;
    Object_4001: THREE.Mesh;
    Object_5001: THREE.Mesh;
    Object_2: THREE.Mesh;
    ["Material-material"]: THREE.Mesh;
    ["Material_001-material"]: THREE.Mesh;
    ["Material_002-material"]: THREE.Mesh;
    ["Material_002-material001"]: THREE.Mesh;
    ["Material_005-material"]: THREE.Mesh;
    ["Material_008-material"]: THREE.Mesh;
    Monitor_Low_Monitor_0: THREE.Mesh;
    Object_10001: THREE.Mesh;
    Object_11001: THREE.Mesh;
    Object_4002: THREE.Mesh;
    Object_5002: THREE.Mesh;
    Object_6001: THREE.Mesh;
    Object_7001: THREE.Mesh;
    Object_8: THREE.Mesh;
    Object_9001: THREE.Mesh;
    Object_13: THREE.Mesh;
    Object_14001: THREE.Mesh;
    Object_15: THREE.Mesh;
    Object_16: THREE.Mesh;
    Object_17: THREE.Mesh;
    Object_18: THREE.Mesh;
    Object_19: THREE.Mesh;
    Object_8001: THREE.Mesh;
    Object_9002: THREE.Mesh;
    Object_11002: THREE.Mesh;
    Object_13001: THREE.Mesh;
    Object_14002: THREE.Mesh;
    Object_16001: THREE.Mesh;
    Object_17001: THREE.Mesh;
    Object_19001: THREE.Mesh;
    Object_20: THREE.Mesh;
    Object_22: THREE.Mesh;
    Object_23: THREE.Mesh;
    Object_25: THREE.Mesh;
    Object_26: THREE.Mesh;
    Object_28: THREE.Mesh;
    Object_30: THREE.Mesh;
    Object_5003: THREE.Mesh;
    Object_6002: THREE.Mesh;
    Object_34: THREE.Mesh;
    Object_36: THREE.Mesh;
    Object_38: THREE.Mesh;
    Object_40: THREE.Mesh;
    Object_42: THREE.Mesh;
    Object_44: THREE.Mesh;
    Object_45: THREE.Mesh;
    Object_32: THREE.Mesh;
    Object_49: THREE.Mesh;
    Object_47: THREE.Mesh;
    Object_54: THREE.Mesh;
    Object_56: THREE.Mesh;
    Object_58: THREE.Mesh;
    Object_59: THREE.Mesh;
    Object_61: THREE.Mesh;
    Object_63: THREE.Mesh;
    Object_65: THREE.Mesh;
    Object_67: THREE.Mesh;
    Object_69: THREE.Mesh;
    Object_71: THREE.Mesh;
    Object_73: THREE.Mesh;
    Object_75: THREE.Mesh;
    Object_77: THREE.Mesh;
    Object_51: THREE.Mesh;
    Object_52: THREE.Mesh;
    Object_79: THREE.Mesh;
  };
  materials: {
    comp_desk_c: THREE.MeshStandardMaterial;
    comp_desk: THREE.MeshStandardMaterial;
    comp_desk_b: THREE.MeshStandardMaterial;
    comp_desk_a: THREE.MeshStandardMaterial;
    comp_desk_2remote: THREE.MeshStandardMaterial;
    comp_desk_1remote: THREE.MeshStandardMaterial;
    comp_desk_button: THREE.MeshStandardMaterial;
    comp_desk_remote: THREE.MeshStandardMaterial;
    comp_desk_top: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
    ["Material.002"]: THREE.MeshStandardMaterial;
    keyboard_texture: THREE.MeshStandardMaterial;
    ["Material.005"]: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshStandardMaterial;
    ["Material.004"]: THREE.MeshStandardMaterial;
    ["Material.006"]: THREE.MeshStandardMaterial;
    ["Material.008"]: THREE.MeshStandardMaterial;
    Monitor: THREE.MeshStandardMaterial;
    ["Material.014"]: THREE.MeshStandardMaterial;
    ["Material.015"]: THREE.MeshStandardMaterial;
    ["Material.007"]: THREE.MeshStandardMaterial;
    ["Material.009"]: THREE.MeshStandardMaterial;
    ["Material.010"]: THREE.MeshStandardMaterial;
    ["Material.011"]: THREE.MeshStandardMaterial;
    ["Material.012"]: THREE.MeshStandardMaterial;
    ["Material.013"]: THREE.MeshStandardMaterial;
    ["Material.016"]: THREE.MeshStandardMaterial;
    ["Material.017"]: THREE.MeshStandardMaterial;
    ["Material.018"]: THREE.MeshStandardMaterial;
    ["Material.019"]: THREE.MeshStandardMaterial;
    ["Material.020"]: THREE.MeshStandardMaterial;
    ["Material.021"]: THREE.MeshStandardMaterial;
    black_skin: THREE.MeshStandardMaterial;
    outline: THREE.MeshStandardMaterial;
    black_plactic: THREE.MeshStandardMaterial;
    metal: THREE.MeshStandardMaterial;
    ["Material.022"]: THREE.MeshStandardMaterial;
    ["Material.023"]: THREE.MeshStandardMaterial;
  };
};

export default function MySetup(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("mySetup/mySetup.gltf") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.comp_desk_c}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.comp_desk}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.comp_desk_b}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials.comp_desk_a}
        />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_10.geometry}
          material={materials.comp_desk_2remote}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11.geometry}
          material={materials.comp_desk_1remote}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_12.geometry}
          material={materials.comp_desk_button}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials.comp_desk_remote}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_14.geometry}
        material={materials.comp_desk_top}
      />
      <group
        position={[-0.00293, 0.78652, 0.11756]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={-0.03081}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[0, 1.69543, 0]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={[-13.88797, -0.08749, -6.6668]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_4001.geometry}
              material={materials["Material.001"]}
              position={[0.01075, 0.07492, -0.07078]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_5001.geometry}
              material={materials["Material.002"]}
              position={[0.01075, 0.07492, -0.07078]}
            />
          </group>
        </group>
      </group>
      <group
        position={[-0.10601, 0.77787, 0.15438]}
        rotation={[-Math.PI / 2, 0, -0.0015]}
        scale={1.53035}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.keyboard_texture}
          position={[0.0082, -0.00458, -0.01066]}
        />
      </group>
      <group
        position={[0.30149, 0.73143, 0.15875]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.01879}
      >
        <group
          position={[0, 0, 0.16883]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={2.16481}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Material-material"].geometry}
            material={materials["Material.005"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Material_001-material"].geometry}
            material={materials["Material.003"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Material_002-material"].geometry}
            material={materials["Material.004"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Material_002-material001"].geometry}
            material={materials["Material.004"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Material_005-material"].geometry}
            material={materials["Material.006"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Material_008-material"].geometry}
            material={materials["Material.008"]}
          />
        </group>
      </group>
      <group
        position={[0.00007, 0.98873, -0.16865]}
        rotation={[-Math.PI / 2, 0, 1.55241]}
      >
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group
            position={[-0.9216, 25.34686, -0.03217]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 99.99999, 99.99999]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Monitor_Low_Monitor_0.geometry}
              material={materials.Monitor}
              position={[0.01163, 0.00324, -0.24633]}
              rotation={[0, 0, 0.01948]}
              scale={[1.00005, 1.14246, 1]}
            />
          </group>
        </group>
      </group>
      <group
        position={[-0.61236, 0.74945, -0.14058]}
        rotation={[-Math.PI / 2, 0, -1.01322]}
        scale={0.09968}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-1.1986, 0.09598, 0]} rotation={[0, 0, -1.38024]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_10001.geometry}
              material={materials["Material.014"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_11001.geometry}
              material={materials["Material.015"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_4002.geometry}
              material={materials["Material.007"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_5002.geometry}
              material={materials["Material.009"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6001.geometry}
              material={materials["Material.010"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_7001.geometry}
              material={materials["Material.011"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_8.geometry}
              material={materials["Material.012"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_9001.geometry}
              material={materials["Material.013"]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_13.geometry}
            material={materials["Material.016"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_14001.geometry}
            material={materials["Material.017"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_15.geometry}
            material={materials["Material.017"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_16.geometry}
            material={materials["Material.018"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_17.geometry}
            material={materials["Material.019"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_18.geometry}
            material={materials["Material.020"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_19.geometry}
            material={materials["Material.021"]}
          />
        </group>
      </group>
      <group
        position={[0, 0, 1]}
        rotation={[-Math.PI / 2, 0, 3.13977]}
        scale={1.26752}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[0.16841, 0.3592, -0.06369]}
            rotation={[-0.12017, 0.05116, -0.40059]}
            scale={0.25492}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_8001.geometry}
              material={materials.black_skin}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_9002.geometry}
              material={materials.outline}
            />
          </group>
          <group
            position={[0.03338, 0.07866, 0.05146]}
            rotation={[0, -0.7124, 0]}
            scale={[0.02009, 0.02009, 0.01795]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_13001.geometry}
              material={materials.black_plactic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_14002.geometry}
              material={materials.outline}
            />
          </group>
          <group
            position={[0.039, 0.07838, -0.00528]}
            rotation={[0, 0.38903, 0]}
            scale={[0.02009, 0.02009, 0.01795]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_16001.geometry}
              material={materials.black_plactic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_17001.geometry}
              material={materials.outline}
            />
          </group>
          <group
            position={[-0.05126, 0.07838, -0.00009]}
            rotation={[Math.PI, 0.3285, 0]}
            scale={[-0.02009, -0.02009, -0.01795]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_19001.geometry}
              material={materials.black_plactic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_20.geometry}
              material={materials.outline}
            />
          </group>
          <group
            position={[-0.0064, 0.07838, -0.03608]}
            rotation={[-Math.PI, 1.57053, 0]}
            scale={[-0.02009, -0.02009, -0.01795]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_22.geometry}
              material={materials.black_plactic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_23.geometry}
              material={materials.outline}
            />
          </group>
          <group
            position={[-0.04015, 0.07838, 0.05445]}
            rotation={[Math.PI, -0.88239, Math.PI]}
            scale={[0.02009, 0.02009, 0.01795]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_25.geometry}
              material={materials.black_plactic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_26.geometry}
              material={materials.outline}
            />
          </group>
          <group
            position={[0, 0.52641, 0.04462]}
            scale={[0.15399, 0.20166, 0.25492]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_5003.geometry}
              material={materials.black_skin}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6002.geometry}
              material={materials.outline}
            />
          </group>
          <group
            position={[0.24485, 0.33998, 0.14811]}
            scale={[0.01173, 0.00573, 0.01701]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_44.geometry}
              material={materials.black_skin}
              position={[0, -0.00001, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_45.geometry}
              material={materials.metal}
              position={[0, -0.00001, 0]}
            />
          </group>
          <group
            position={[0.24529, 0.58406, 0.1657]}
            scale={[0.1688, 0.25492, 0.26556]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_58.geometry}
              material={materials.black_skin}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_59.geometry}
              material={materials.outline}
            />
          </group>
          <group
            position={[0.19113, 0.35628, -0.11333]}
            rotation={[-0.12285, 0.1768, -1.5277]}
            scale={0.01274}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_61.geometry}
              material={materials["Material.023"]}
              position={[0, 0, 0]}
            />
          </group>
          <group
            position={[0.1962, 0.35623, -0.11425]}
            rotation={[-0.11899, 0.17941, -1.54947]}
            scale={0.01274}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_67.geometry}
              material={materials["Material.023"]}
              position={[0, 0, -0.00001]}
            />
          </group>
          <group
            position={[0.1962, 0.35623, -0.11425]}
            rotation={[-0.11899, 0.17941, -1.54947]}
            scale={0.01274}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_71.geometry}
              material={materials["Material.023"]}
              position={[0, 0, -0.00001]}
            />
          </group>
          <group
            position={[-0.00537, 0.88478, -0.2397]}
            rotation={[1.50179, 0, 0]}
            scale={0.00812}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_75.geometry}
              material={materials.black_skin}
              position={[0, -0.00002, -0.00001]}
            />
          </group>
          <group
            position={[-0.0061, 0.77445, -0.17781]}
            rotation={[1.60542, 0, 0]}
            scale={[0.13179, 0.1429, 0.09603]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_51.geometry}
              material={materials.black_skin}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_52.geometry}
              material={materials.outline}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_11002.geometry}
            material={materials.black_skin}
            position={[-0.00774, 0.57131, -0.12908]}
            rotation={[-0.20751, 0, 0]}
            scale={[0.11925, 0.11474, 0.09287]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_28.geometry}
            material={materials.black_plactic}
            position={[-0.00467, 0.07725, 0.01627]}
            rotation={[0, -0.34261, 0]}
            scale={[0.06124, 0.03403, 0.06124]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_30.geometry}
            material={materials.black_plactic}
            position={[-0.13108, 0.29102, 0.07351]}
            rotation={[Math.PI, -0.4515, Math.PI]}
            scale={[0.36014, 0.41179, 0.36014]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_34.geometry}
            material={materials.black_plactic}
            position={[-0.19112, 0.01579, 0.23779]}
            rotation={[Math.PI / 2, 0, -0.87633]}
            scale={0.28258}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_36.geometry}
            material={materials.black_plactic}
            position={[0.21392, 0.01811, 0.20641]}
            rotation={[-Math.PI / 2, 0, -0.7295]}
            scale={-0.28258}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_38.geometry}
            material={materials.black_plactic}
            position={[0.26515, 0.01579, -0.09845]}
            rotation={[-Math.PI / 2, 0, 0.4347]}
            scale={-0.28258}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_40.geometry}
            material={materials.black_plactic}
            position={[-0.00563, 0.01579, -0.27632]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={-0.28258}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_42.geometry}
            material={materials.black_plactic}
            position={[-0.27502, 0.01579, -0.07663]}
            rotation={[Math.PI / 2, 0, 0.31478]}
            scale={0.28258}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_32.geometry}
            material={materials.black_plactic}
            position={[-0.00411, 0.14123, 0.01537]}
            scale={0.02835}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_49.geometry}
            material={materials.black_plactic}
            position={[-0.00437, 0.31252, 0.11736]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[1.63733, 1.06337, 1.06337]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_47.geometry}
            material={materials.black_plactic}
            position={[-0.00439, 0.27547, 0.17839]}
            rotation={[3.12877, 0, Math.PI]}
            scale={[1.06337, 0.9073, 1.00413]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_54.geometry}
            material={materials.black_skin}
            position={[0.06019, 0.92223, -0.22139]}
            rotation={[1.52519, 0, 0]}
            scale={[0.03825, 0.03369, 0.03752]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_56.geometry}
            material={materials["Material.022"]}
            position={[-0.00467, 0.8834, -0.18904]}
            rotation={[1.3812, 0, 0]}
            scale={[0.11839, 0.08656, 0.07932]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_63.geometry}
            material={materials["Material.023"]}
            position={[0.18668, 0.35623, -0.11251]}
            rotation={[-0.11899, 0.17941, -1.54947]}
            scale={0.01274}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_65.geometry}
            material={materials["Material.023"]}
            position={[0.18668, 0.35623, -0.11251]}
            rotation={[-0.11899, 0.17941, -1.54947]}
            scale={0.01274}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_69.geometry}
            material={materials["Material.023"]}
            position={[-0.19018, 0.52544, -0.12986]}
            rotation={[-0.12592, 0.07465, -1.48079]}
            scale={0.01274}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_73.geometry}
            material={materials.outline}
            position={[0.06972, 0.58493, -0.07401]}
            rotation={[1.29343, 0, 0]}
            scale={[0.01878, 0.07908, 0.07908]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_77.geometry}
            material={materials.outline}
            position={[-0.00467, 0.8834, -0.18904]}
            rotation={[1.3812, 0, 0]}
            scale={[0.11839, 0.08658, 0.07988]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_79.geometry}
            material={materials.outline}
            position={[-0.05086, 1.04125, -0.20524]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.03758}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("mySetup/mySetup.gltf");
